# .github/workflows/update-version.yml
name: Otomatik version.txt güncelle

on:
  release:
    types: [published]

jobs:
  update-version-file:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu çek
        uses: actions/checkout@v3

      - name: Sürüm numarasını al
        id: get_version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: version.txt dosyasını oluştur
        run: |
          echo "$RELEASE_VERSION" > version.txt
          echo "https://github.com/${{ github.repository }}/releases/download/$RELEASE_VERSION/publish.zip" >> version.txt

      - name: AssemblyInfo.cs sürümünü güncelle
        run: |
          sed -i -E "s/AssemblyVersion\(\"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\"\)/AssemblyVersion(\"$RELEASE_VERSION\")/" Properties/AssemblyInfo.cs
          sed -i -E "s/AssemblyFileVersion\(\"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\"\)/AssemblyFileVersion(\"$RELEASE_VERSION\")/" Properties/AssemblyInfo.cs

      - name: Git ayarları
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit ve push
        run: |
          git add version.txt Properties/AssemblyInfo.cs
          git commit -m "Sürüm güncellendi -> $RELEASE_VERSION"
          git push
